### ISSUE TITLE
Shiba shows nothing

### ISSUE THREAD

**Issue by six-star** [rhysd/Shiba#43] opened 2018-05-08 20:47 UTC
###### What happened:
Shiba shows nothing in the markdown drawing area.

###### What did you expect to happen:
I have used Shiba from version 1.1.1. It's nice preview application for markdown!. It had no problem. But Shiba shows nothing after I updated it to version 1.2.0. I'm using md files which is ok on version 1.1.1. 
I don't use custom config.yml.

###### How to reproduce it (as minimally and precisely as possible):
I replaced all file to version 1.2.0 from version 1.1.1 in Shiba-win32-x64 folder, and open *.md file.

###### Environment:
+ Shiba version: 1.2.0 Shiba-win32-x64
+ OS version: Windows 10 64bit (1709)

**Comment by rhysd** [comment] 2018-05-09 04:03
Thank you for reporting this. Let me confirm one thing. You installed Shiba by downloading an archive from releases page on GitHub, is it correct? I need to reproduce this issue to resolve.

**Comment by six-star** [comment] 2018-05-09 14:28
Yes, I got it from releases page.
This issue is the same even if I starts it after removing Shiba folder in AppData\Roaming.

And I tried version 1.1.2. In case of 1.1.2 it has no problem.

**Comment by hogewest** [comment] 2018-05-15 05:15
I am experiencing the same problem.

An error was output to Developer Tools.
```
module.js:487 Uncaught Error: Cannot find module 'marked'
    at Module._resolveFilename (module.js:485)
    at Function.Module._resolveFilename (C:\bin\Shiba\resources\electron.asar\common\reset-search-paths.js:35)
    at Function.Module._load (module.js:437)
    at Module.require (module.js:513)
    at require (internal/module.js:11)
    at markdown-preview.ts:8
```

There seems to be no **marked** module.

```cmd
$ asar extract resources\app.asar app
$ dir app\node_modules | findstr "marked"
2018/05/15  14:05    <DIR>          marked-sanitizer-github
```

**Comment by rhysd** [comment] 2018-05-15 12:09
@six-star @hogewest 

https://github.com/rhysd/Shiba/releases/tag/v1.2.0

I built packages with a fixed script. At least on Mac it works and I'll confirm behavior on Windows tomorrow. Please try them.

**Comment by rhysd** [comment] 2018-05-16 04:43
I confirmed this was fixed with my Windows machine.

**Closed by rhysd** 2018-05-16 04:43 UTC
Labels: bug

**Comment by hogewest** [comment] 2018-05-16 07:44
I confirmed fixed.
Thanks! 😄
