### ISSUE TITLE
Printing to PDF on Windows is not working

### ISSUE THREAD

**Issue by BagelTheKid** [rhysd/Shiba#33] opened 2016-09-13 20:00 UTC
Whenever I am attempting to print to pdf on Windows, my machine uses bioPDF to print to pdf. I am able to print a test page with bioPDF, and can print to pdf using Word. I'm unsure if the issue is truly with Shiba, or bioPDF.

**Comment by rhysd** [comment] 2016-09-14 15:20
I'll check with my Windows machine tomorrow :smiley:

**Comment by Naramsim** [comment] 2016-09-22 07:32
Me too, using default PDF Printer

**Comment by rhysd** [comment] 2016-09-26 16:24
Sorry for latency. I confirmed below points for this issue.

- Shiba can't print on Window8.1
- [DemoApp](https://github.com/electron/electron-api-demos) can print on Windows8.1
- Shiba can print on OS X 10.11.6

Electron version is 1.4.1 for Shiba, and DemoApp's Electron version looks old.  I need to check this on latest Electron.app.

**Comment by rhysd** [comment] 2016-09-28 02:29
Electron v1.4.1 on Windows is also OK.  So I confirmed this is an issue of Shiba.

**Comment by BagelTheKid** [comment] 2017-10-02 20:22
Hello, any update to this issue? Thanks.

**Comment by rhysd** [comment] 2017-10-03 06:57
I confirmed this issue again with the latest.

Now it seems to work on Electron v1.7.8. I tried to print a markdown document to PDF file as following.

![default](https://user-images.githubusercontent.com/823277/31113268-6ac36442-a853-11e7-8f64-d44aa1675654.JPG)

I'll release Shiba v1.0.5 for large dependencies updates.

**Comment by rhysd** [comment] 2017-11-03 16:23
I'm closing this issue because v1.1.0 was released. If someone notices this issue still occurs, please let me know by leaving a comment here.

**Closed by rhysd** 2017-11-03 16:23 UTC
